### ISSUE TITLE
Users are uploading multiple primary pdfs because the PDF "disappears"

### ISSUE THREAD

**Issue by amiles4** [emory-libraries/etd-issues#13]
We have figured out that students are able to upload multiple primary pdfs. While this is not possible within the My PDF tab when they first encounter it, if they find that they have uploaded the wrong pdf in the generated preview under Review & Submit, they are able to go back to the My PDF tab and upload another before submitting.

In other words, after generating the preview, the previously uploaded pdf file is no longer visible under the My PDF tab and a second, third, fourth, and so on can be uploaded. All additional files are then visible in the generated preview but cannot be deleted. Attached is a screenshot where I was able to upload many files on a singular record by generating the preview and then returning to My PDF and then generating again. The pid for this example in staging is m613mx563.

We know how to delete duplicate pdfs on our own once they have submitted, so no rush, just making you all aware that this is happening.

This is also a Freshdesk ticket #33: https://curationexperts.freshdesk.com/support/tickets/33
![Screen Shot 2017-11-08 at 12.48.20 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a28483d64e0480012d30b31/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76226454fb6b7191a379ed0c2f59415d4ebc21254d58eeb9cb74fce36f34985619e8806f5770c23515faed801cba06ba208a1d85beb4de1ac5fa2137a5dad11b61435c52dcbd4f3fb2984cc259f34ae34b53a0123e6be170366e0a.png)

**Comment by amiles4** [comment]
Finally we are seeing this issue in production with students. I have two examples where students somehow found the infinite pdf loop. The first is Allison Lin's record with three pdfs attached: https://etd.library.emory.edu/concern/etds/4t64gn212
![Screen Shot 2018-04-10 at 9.59.09 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a28483d64e0480012d30b31/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276455f36b7191a371f117224f5f565edd3c4a4356bcbbd671f3e57862804e0ebcd3655b70ce3947f9ba811ab801ba21d94f8dbee8dc49d2f42f67b6d5db1063474f4dcbed5727a19041c95df448e24b5da314356ae4732431.png)

**Comment by amiles4** [comment]
The second is Kathleen O'Keefe with two pdfs attached: https://etd.library.emory.edu/concern/etds/bk1289934
![Screen Shot 2018-04-10 at 10.00.22 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a28483d64e0480012d30b31/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276455f36b7191a379ef0c2b51415d4cbc30254d58eeb9cb74fce36f34985619e8806f5770c23515faed801cba06ba208a1d85beb4de1ac5fa2137a5dad11b61435c52dcbd4f3fb2984cc259f349e24e53ac1b3563ef70366e0a.png)

**Comment by amiles4** [comment]
A third from Carli Kovel: https://etd.library.emory.edu/concern/etds/zs25x846c
![Screen Shot 2018-04-10 at 11.02.08 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a28483d64e0480012d30b31/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276455f36b7191a379ee0c2b53415f46bc30254d58eeb9cb74fce36f34985619e8806f5770c23515faed801cba06ba208a1d85beb4de1ac5fa2137a5dad11b61435c52dcbd4f3fb29843c259f349e24e52a616336be5763e6e0a.png)

**Comment by amiles4** [comment]
A fourth from Michael Demers: https://etd.library.emory.edu/concern/etds/37720c75x
![Screen Shot 2018-04-10 at 12.29.48 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a28483d64e0480012d30b31/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276455f36b7191a379ed0c2958415b46bc21254d58eeb9cb74fce36f34985619e8806f5770c23515faed801cba06ba208a1d85beb4de1ac5fa2137a5dad11b61435c52dcbd4f3fb29843c259f349e24e52a31b3565ef7f336e0a.png)

**Comment by amiles4** [comment]
@rosy1280 says: this may be fixed by removing the tabs and developing a more inline workflow. (i.e. UI enhancements that remove some of the enhancements we made).

**Comment by rosy1280** [comment]
Can we add language that says their pdf is being uploaded and will appear soon.
