### ISSUE TITLE
Edit an embargo with an arbitrary date

### ISSUE THREAD

**Issue by fpici** [emory-libraries/etd-issues#15]
Desired Enhancement - we would really like to have the ability to edit an existing embargo with an arbitrary date and not necessarily be limited to  choosing durations of 1 year, 2 year, 3 years. This way we could select a 30 day embargo for an alum who is waiting for advisor approval to extend their current date OR have the option to choose a 6 month duration for alum who do not want an entire year.

**Comment by fpici** [comment]
This may be tied to our Migration Tool work.

**Comment by rosy1280** [comment]
This may be resolved or improved with https://github.com/curationexperts/laevigata/issues/1035

**Comment by fpici** [comment]
I believe this was taken care of during the 2.0 upgrade :-)
