### ISSUE TITLE
Improvements to the Admin and Approver Notifications View

### ISSUE THREAD

**Issue by amiles4** [emory-libraries/etd-issues#17]
Currently the User Notifications field available to students, approvers, and admins is a long block of text that is not sortable. While this is not a major issue, it is a significant burden for approvers with many records to review and for admins when trying to find a specific student's submission. The work around right now is to try to do a CTRL+F/⌘+F on the title or the student name.           
Bear in mind that when a record is initially submitted, the notification includes the author's name and the PID. However, as soon as the record's status changes (i.e. requires changes, approved, pending approval, pending review), the author name disappears in the notification and only the record's  title and PID remains. This can be problematic for Admin/Approver, especially if the student has changed their record's title.

Would it be possible to view and to sort the notifications by name of student, status of record (i.e. requires changes, approved, pending approval, pending review), and by date?

**Comment by amiles4** [comment]
![Screen Shot 2018-01-09 at 10.31.08 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a28483d64e0480012d30b31/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77226454fa6b7191a379ef0c2850415f46bc30254d58eeb9cb74fce36f34985619e8806f5770c23515faed801cba06ba208a1d85beb4de1ac5fa2137a5dad11b61435c52dcbd4f3fb2984cc259f34ae44854a616316be072356e0a.png)

**Comment by rotated8** [comment]
We can add a new item to the dashboard tab for Approvers to do this. This will be a large task, and will take a while (and more tickets) to implement.

**Comment by amiles4** [comment]
ADAPs/Approvers do not have access to the Administration tab at this time. One function that is immensely helpful in the Administration tab is the ability to open an admin set and see all works submitted within that admin set. Working with an ADAP over the phone, I was unable to explain the CTRL+F/⌘+F search method to her and she seemed unable to search her emails either. I had to go into the admin set myself to download all of the individual files submitted this semester within that specific department. If we could make the search function easier on the Notifications tab or create a similar space in the Dashboard to the one we see as Admins, that would be ideal. See the below screenshot for an example of how this looks in the Admin tab.

**Comment by amiles4** [comment]
![Screen Shot 2018-05-11 at 9.54.42 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a28483d64e0480012d30b31/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266455f26b7191a371f1172f4f5b5d5edd3c4a4356bcbbd671f3e57862804e0ebcd3655b70ce3947f9ba811ab801ba21d94f8dbee8dc49d2f42f67b6d5db1063474f4dcbed5727a19e41c95df44de14953ad153067e17f2431.png)

**Comment by rosy1280** [comment]
[ ] add a column with the name of the user submitting a work to the notifications screen
[ ] add a column with the name of the user that submitted a work to the works in this set screen
[ ] make the columns sortable on both the notifications screen and the works in this set screen

**Comment by rosy1280** [comment]
portions of this are included in the upgrade, but the addition of names may be easily done.

**Comment by fpici** [comment]
@rosy1280 Yes. The upgrade did help with these notifications BUT having the UserName or Depositor added to the notifications would be great!

**Comment by devanshu-m** [comment]
@fpici I was trying to see how notifications are displayed currently and I think the `message` includes depositor display_name. Please refer screenshot below and correct me if I am misunderstanding this.

![Screen Shot 2018-11-02 at 4.17.21 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b2aa58d159b700013eb453c/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226454f16b7191a37cf1132c4f5d5e5ecc3c4a4356bcbbd671f3e57862804e0ebcd3655b70ce3947f9ba811ab801ba21d94f8dbee8dc49d2f42f67b6d5db1063474f4dcbed5727a29841c95df24ae04455a7143162e0772431.png)

**Comment by fpici** [comment]
Good Morning Devanshu.

Yes. The depositor's name is only displayed on the initial submission action. Whenever Changes are Required, or a record is Pending or Approved, the Name no longer appears in the notification. Super Admins and Approvers have requested that we have a column to sort by Depositor name. Let me know if that helps.

**Comment by rotated8** [comment]
A new column is not possible at this time. We will add the users name to the message body. Admins can use the search feature.

**Comment by rotated8** [comment]
Yes.
