### ISSUE TITLE
Add Google Analytics to the new ETD site

### ISSUE THREAD

**Issue by fpici** [emory-libraries/etd-issues#19]
From Emily Porter: Looks like we haven’t added Google Analytics to the new ETD application. Have we already talked about how to transition Google Analytics on ETDs? My suggestion is only related to the basic Google Analytics tracking code snippet (and existing Google Analytics account), and whether or not we want to relocate that HTML code snippet over to the new application from the old one?

From Rosalyn:
While Google Analytics information is useful to have, do we want to prioritize that work over the other items on this list? Or do we want to add a ticket to the backlog and lump it with everything else?
Also in Waffle laevigata Ticket# 749

**Comment by rotated8** [comment]
In Freshdesk as ticket #38

**Comment by rotated8** [comment]
This ticket has been passed on to DCE, so I've updated the labels to reflect that.

**Comment by amiles4** [comment]
@rosy1280 says: Follow up with DCE about adding analytics to the application.
