### ISSUE TITLE
Remove Ulf Nilsson from ETD email notifications

### ISSUE THREAD

**Issue by fpici** [emory-libraries/etd-issues#2]
Remove Nilsson, Ulf -- Assoc Dean of Laney Graduate School --  (unilsso@emory.edu) from ETD email notifications.

**Comment by fpici** [comment]
Hi folks. Any timetable for when y'all think this can be completed? Ulf has sent another email requesting this be taken care of sooner rather than later?  So sorry to pester... :-)

**Comment by rotated8** [comment]
Added to Freshdesk as #37
