### ISSUE TITLE
Add Permanent Embargo to our list of Embargo options for Superusers only.

### ISSUE THREAD

**Issue by fpici** [emory-libraries/etd-issues#21]
Note: Not sure if we should add this to DCE Embargo work or if it is something Zo and Collin can address separately??
On rare occasions we need to set a permanent embargo on a thesis or dissertation for the student's protection. This is an option we want to have for the Superuser ONLY and this option should NOT be visible to the student uploader.

**Comment by fpici** [comment]
This is probably tied into our Migration Tool work.

**Comment by rosy1280** [comment]
This may be resolved or improved with https://github.com/curationexperts/laevigata/issues/1035

**Comment by rosy1280** [comment]
The capability to keep something private (aka a permanent embargo) may already exist in Hyrax.  DCE can investigate this.
