### ISSUE TITLE
Add the "File Size" display in published record

### ISSUE THREAD

**Issue by fpici** [emory-libraries/etd-issues#22]
VERY LOW LIMBOESQUE Priority: As a public and Admin ETD user, I want to see the "File Size" displayed on an ETD record, so I can easily see how big the file is.  *This feature was present in legacy ETDs and I believe was auto-calculated by the pdf properties in the technical metadata (see screenshot). It is a NON-Editable field. It falls under feature parity. I think we may need to add this and/or make sure it is a part of the bigger HYRAX buildout :-)

**Comment by fpici** [comment]
![Screen Shot 2018-01-29 at 11.42.51 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58efcaa2b7100d001a59b5e8/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77226456fa6b7191a379ee0c2f53415a4fbc30254d58eeb9cb74fce36f34985619e8806f5770c23515faed801cba06ba208a1d85beb4de1ac5fa2137a5dad11b61435c52dcbd4f3fb29842c259f34ae64f51a011356be374376e0a.png)

**Comment by rotated8** [comment]
Do you expect many users to ask for this feature if it is missing?

**Comment by fpici** [comment]
@rotated8 The number of pages was present in legacy ETDs and something that was/is useful for Approvers, Depositors, and the public View for Users. Feature Parity is the goal here. I am not sure if users would notice its absence BUT it is something that is important to make visible :-)

**Comment by fpici** [comment]
@rotated8 I modified this slightly to reflect the "File Size" display and NOT the number of pages :-) Also changed to super LOW priority.

**Comment by rosy1280** [comment]
we have discussed closing this ticket in the past because the information shows up in the fileset page rather than the work. i.e. users can see this information if they need to see it.

**Comment by rotated8** [comment]
Closing in light of the above comment.
