### ISSUE TITLE
Language changes to User Publication Status notification

### ISSUE THREAD

**Issue by fpici** [emory-libraries/etd-issues#23]
A couple of fall 2017 grads have contacted me  after checking on the publication status of their thesis or diss. The message they see when they click on their PID says: "The work is not currently available because it has not yet completed the approval process." This is inaccurate and confusing. I suggest changing the message to something like: "The work is unavaliable because it has not completed the publishing process."  See screenshot

**Comment by fpici** [comment]
![Screen Shot 2018-01-30 at 8.31.26 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58efcaa2b7100d001a59b5e8/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77226457f36b7191a370f1112a4f5d595edd3c4a4356bcbbd671f3e57862804e0ebcd3655b70ce3947f9ba811ab801ba21d94f8dbee8dc49d2f42f67b6d5db1063474f4dcbed5727a19041c95df74ce24f57a0123f60e27f2431.png)

**Comment by rotated8** [comment]
@fpici: This comes from Hyrax, where it is translated into seven languages (English, German, Spanish, French, Italian, Brazilian Portuguese,  and Chinese). Should this be changed in all of them? if so, is there a better translation source than Google Translate available?

**Comment by rotated8** [comment]
Talked with @fpici and we agreed to only change the English translation, as the dropdowns we've added only have English text at the moment. (Additionally, we are currently on Hyrax 1.0.5, so only have English, Spanish, and Chinese Hyrax translations at the moment.)
