### ISSUE TITLE
DRAFT: May need to consider sending files to Proquest when the abstract/TOC are also embargoed.

### ISSUE THREAD

**Issue by fpici** [emory-libraries/etd-issues#24]

**Comment by fpici** [comment]
PQ just replied to a Lisa email and said: "ProQuest’s practice is to embargo the full text of the dissertation when an embargo is requested.  During the time of the embargo, the metadata (including abstract) is made available via ProQuest and the 35 subject and index partners to whom ProQuest provides data." 

More on this coming soon :-)

**Comment by rotated8** [comment]
I think this has been fixed by DCE. Is that true?

**Comment by fpici** [comment]
@rotated8 Yes. I believe this was addressed by DCE. Laevigata Tix 879 and 880. I have not tested yet but it looks like DCE closed them out :-)
