### ISSUE TITLE
Make ETD Permanent URL visible to the public.

### ISSUE THREAD

**Issue by fpici** [emory-libraries/etd-issues#26]
As an ETD public viewer, I want to see the permanent URL for the record visible on the published record, so I can easily copy and paste it to friends, family, and facebook :-) (see screenshot of legacy ETDs)

**Comment by fpici** [comment]
![Screen Shot 2018-02-28 at 11.41.48 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58efcaa2b7100d001a59b5e8/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216456fb6b7191a379ee0c2f50415b46bc30254d58eeb9cb74fce36f34985619e8806f5770c23515faed801cba06ba208a1d85beb4de1ac5fa2137a5dad11b61435c52dcbd4f3fb29843c259f34ae84551a3113f61e1713f6e0a.png)

**Comment by fpici** [comment]
![Screen Shot 2018-02-28 at 11.37.43 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58efcaa2b7100d001a59b5e8/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216456fb6b7191a379ee0c2856415b4dbc30254d58eeb9cb74fce36f34985619e8806f5770c23515faed801cba06ba208a1d85beb4de1ac5fa2137a5dad11b61435c52dcbd4f3fb29842c259f34ae84551a3103664e573376e0a.png)

**Comment by rotated8** [comment]
Since we aren't using Pidman, the permanent URL is the one in the browser's location bar. Is it necessary to show that URL again?

**Comment by fpici** [comment]
@rotated8 This is a feature parity issue and I think a good one to retain since it is an obvious visual for Depositors, Faculty, and Public users to easily share the link to the work. :-)
