### ISSUE TITLE
Students cannot remove or edit submitted primary PDF and already submitted supplemental files.

### ISSUE THREAD

**Issue by fpici** [emory-libraries/etd-issues#27]
In Dec 2017, Bess told us that the primary PDF and already submitted supplemental files cannot be removed or edited. If a student wishes to replace those files they should re-submit their entire ETD or ask for help from Fran or Anna. The ETD sites have the below message (see screenshot) that notifies the submitter of this and what they will need to do. Can we find out if this is something the student will be able to do soon?

**Comment by fpici** [comment]
Here is a screenshot of the message :-)
![Screen Shot 2018-03-13 at 3.09.15 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58efcaa2b7100d001a59b5e8/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206455f06b7191a37bf112224f5e5a5ecc3c4a4356bcbbd671f3e57862804e0ebcd3655b70ce3947f9ba811ab801ba21d94f8dbee8dc49d2f42f67b6d5db1063474f4dcbed5727a19041c95df44ae14856a3173e62e1772431.png)

**Comment by rotated8** [comment]
Students can send files to Fran/Anna and they can replace the files.

**Comment by fpici** [comment]
@rotated8 Sorry Collin. I accidentally closed this ticket. Can you open it again? Or show me how to open it. Sorry :-(

**Comment by fpici** [comment]
@rotated8 Never mind. I figured it out and re-opened this :-)

**Comment by fpici** [comment]
This work is closely related to laevigata Tix 927: https://waffle.io/curationexperts/laevigata/cards/5ab032e9b58dde001b306ec2
:-)

**Comment by amiles4** [comment]
@rosy1280 says: when an approver rejects an ETD submission, they should be able to resubmit the file and delete the older file.

**Comment by amiles4** [comment]
@rotated8 says: we need to have access to the file manager when the ETD is put into the status changed (?)

**Comment by rosy1280** [comment]
this may be related to https://github.com/curationexperts/laevigata/issues/1080

**Comment by rosy1280** [comment]
file manager doesn't allow you to upload new files when an ETD is put into a new status.

**Comment by fpici** [comment]
I believe this was taken care of in the 2.0 upgrade 8.24.2018 :-)
