### ISSUE TITLE
Rollins Dropdown/Fields & Subfields are NOT displaying as requested in attached Rollins Schools Programs/subfields spreadsheet

### ISSUE THREAD

**Issue by fpici** [emory-libraries/etd-issues#3]
Rollins Dropdown Fields & Subfields do not match what s in the RollinsSchoolsPrograms spreadsheet. The Rollins School Approvers ask that we rebuild their school dropdown to include the Subfields as requested in the attached spreadsheet. The students are confused when they submit and in Legacy ETDs, the dropdown included a Subfield that was associated with the Department. See attached spreadsheet

**Comment by fpici** [comment]
[Copy of RollinsSchoolProgramsSubRevisions1HighlightedMissing.xlsx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58efcaa2b7100d001a59b5e8/125516c66e82c728ace21e0d46cb9b8a3ac28cafcfdbb04fa854fe871a452f7c260893397f82f129b25148140d3d1bea181b061ba2ba8853ffe1642cd30b53a98439222d857e48f2ef9003ad41f87fd11ad6f2ae805ec5b93f2de38f874b684b071b8cf85d35a1cb4bc050a21de45f49b651673db2296b250dc15c672679662ea1fdda57858069a5b916285fc0e7f6b7.xlsx)

**Comment by alexBLR** [comment]
Ok. I started working on this one @fpici

**Comment by fpici** [comment]
@alexBLR Using Chrome and Firefox, the following Subfields are missing from Rollins School: 1) Executive Masters of Public Health - MPH - All 6 of the subfields are missing.
2) Environmental Health - All 3 of the subfields are missing.

Everything else looks good. Hope this helps!

**Comment by fpici** [comment]
@alexBLR Hi Zo. The fixes were deployed to ETD QA. I checked and they all look great!! Thank Thank you

**Comment by fpici** [comment]
@alexBLR Changes deployed to Production look FABULOUS! Thank you!
