### ISSUE TITLE
ETD Upcoming Embargo Report for December Graduates

### ISSUE THREAD

**Issue by amiles4** [emory-libraries/etd-issues#30]
As an ETD Admin, I want to see a report of upcoming embargo expirations, so that I can plan for embargo revision requests.

**Comment by fpici** [comment]
One of our SCO student workers checked this manually and we have a google doc spreadsheet with a tab for "Upcoming Embargoes"  that we created to target these upcoming expirations: 

https://docs.google.com/spreadsheets/d/10G4eYFhtpeCKw8PqQul-ncJPe0mgVkQMyTLfD23cpJA/edit?usp=sharing 

I also contacted 6 students whose embargoes are expiring in July 2018 to see if the system sent them a 60-day notice and so far one has responded that they DID NOT receive a notification. So we will need to prioritize the status of Tix 33 too. 

Many thanks! fran

**Comment by amiles4** [comment]
@fpici is going to wait and see if this is necessary
