### ISSUE TITLE
ETD Alum Embargo Notifications

### ISSUE THREAD

**Issue by fpici** [emory-libraries/etd-issues#33]
As an ETD Alum, I want to receive an email notification when my thesis/dissertation access restriction is set to expire in 60 day, 7 day, and “day of” alerts, so I can  prepare for its release.

**Comment by fpici** [comment]
Refer to Embargo Notifications email: Waffle Tix 208: https://github.com/curationexperts/laevigata/issues/208

**Comment by fpici** [comment]
This is probably tied into the upcoming ESD work

**Comment by amiles4** [comment]
@rotated8 says: are these solved?
@fpici thinks so, but we'll know soon...

**Comment by rotated8** [comment]
@fpici confirms this is working.
