### ISSUE TITLE
Non-Emory affiliation NOT showing in ETD record?

### ISSUE THREAD

**Issue by fpici** [emory-libraries/etd-issues#35]
As a ETD public viewer, I want to see the Non-Emory affiliation associated with the Non-Emory Advisor or Committee member on the public-facing part of the ETD record.

**Comment by fpici** [comment]
Hi Collin and Zo. I looked back at Legacy ETDs and the NON-Emory affiliation does display on the public view of the ETD record (see screenshot #1).
![Screen Shot 2018-04-26 at 11.22.43 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58efcaa2b7100d001a59b5e8/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276456f56b7191a379ee0c2953415b4dbc30254d58eeb9cb74fce36f34985619e8806f5770c23515faed801cba06ba208a1d85beb4de1ac5fa2137a5dad11b61435c52dcbd4f3fb29842c259f349e54a50a3163663e2703e6e0a.png)

**Comment by fpici** [comment]
Collin, ZO. I also include a screenshot #2 of a new ETD record with a NON-Emory affiliation (Pedro Moro) and it does NOT show. I sent this to y'all because it is NOT urgent and falls withing feature parity. I will let you decide if it needs to go to DCE :-)
![Screen Shot 2018-04-26 at 11.46.41 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58efcaa2b7100d001a59b5e8/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276456f56b7191a379ee0c2f57415b4fbc30254d58eeb9cb74fce36f34985619e8806f5770c23515faed801cba06ba208a1d85beb4de1ac5fa2137a5dad11b61435c52dcbd4f3fb29b49c259f349e54a50a315356be170306e0a.png)

**Comment by rotated8** [comment]
This was fixed by DCE.
