### ISSUE TITLE
Change ETD Help language and the Link to ETD Help

### ISSUE THREAD

**Issue by fpici** [emory-libraries/etd-issues#38]
Please change the legacy "etd-help@LISTSERV.CC.EMORY.EDU " link to the new Help Form located here: http://sco.library.emory.edu/etds/help-form.html. 

I find the legacy ETD help link in these places: My PDF tab (Upload Large files), and in Two places on the Supplemental Files Tab.

Also change the language to read: "... contact the ETD team using the Help Form."    

See screenshots of tabs.

**Comment by rosy1280** [comment]
to be done as a temporary fix.  permanent fix is #45

**Comment by rosy1280** [comment]
this should be assigned to devanshu once he's set up with our organization's github.  @rotated8 can you do that?

**Comment by fpici** [comment]
@rotated8 Good Morning. I wonder if we should re-open this ticket since the email address etd-help@LISTSERV.CC.EMORY.EDU  is now showing up in the new development site?

**Comment by rotated8** [comment]
Sure, we can track it in this issue.

**Comment by fpici** [comment]
I am testing the new form in the staging environment located here: https://staging-upgrade-etd.emory.edu/in_progress_etds/45/edit?locale=en and notice that the legacy "etd-help@LISTSERV.CC.EMORY.EDU " link is still present in the "My Files" tab. This will need to be re-directed instead to the new Help Form located here: http://sco.library.emory.edu/etds/help-form.html.


Also Please change the language to read: "... contact the ETD team using the Help Form."
Many thanks in advance

**Comment by devanshu-m** [comment]
Hi @fpici, do you need me to make this change anywhere else apart from the 'My Files' tab?

**Comment by fpici** [comment]
@devanshu-m I think the only place this email exists in the NEW ETD form is the My Files tab :-)

**Comment by fpici** [comment]
Hi Devanshu,

I think the only place this email exists in the NEW ETD form is the My Files tab :-)


Frances Pici
Scholarly Repository Application Support Analyst
Scholarly Communications Office
Emory University Libraries and Information Technology
Robert W. Woodruff Library
540 Asbury Circle
Atlanta, GA 30322
404.727.7673
fpici@emory.edu<mailto:%7Cfpici@emory.edu>

Check out our new websites!
Scholarly Communications http://sco.library.emory.edu/index.html
Research Data http://researchdata.emory.edu/index.html
