### ISSUE TITLE
As a Laney School Administrator and an SCO Admin, I want to see a csv report of all PhD records in new ETDs for the academic year 2017-2018.

### ISSUE THREAD

**Issue by fpici** [emory-libraries/etd-issues#39]
The report should include the following fields: Author's name, faculty advisor, committee members, date of submission, and student program.

**Comment by fpici** [comment]
We ask that these on demand requests from School Admins be completed by LTDS until the DLP buildout of the reporting structure.

**Comment by rosy1280** [comment]
This is assigned to @rotated8 now so that we can get a report for the current year.  @fpici can you provide more information about what they want in a report?

**Comment by fpici** [comment]
@rotated8 Hi Collin. Here is what Rosemary from Laney wants: I am copying this from the original description in the ticket above :-) The report should include the following fields: Author's name, faculty advisor, committee members, date of submission, and student program. Any timetable on when this can be produced?

**Comment by fpici** [comment]
Good Morning folks. Any update on this request? I will need to contact Laney admin with an expected date of delivery :-). Many thanks!

**Comment by alexBLR** [comment]
@fpici I am submitting it for review to DCE today. So, I would assume you'll have it by the end of the week.

**Comment by fpici** [comment]
@alexBLR Thank you Zo!!

**Comment by fpici** [comment]
@alexBLR Good morning Zo. Any update on this report? Many thanks

**Comment by alexBLR** [comment]
@fpici I submitted a code to DCE last Wednesday. They should put it into production soon.

**Comment by fpici** [comment]
@alexBLR Thank you!!
