### ISSUE TITLE
Metadata fields missing when using Chrome

### ISSUE THREAD

**Issue by fpici** [emory-libraries/etd-issues#4]
Using Chrome, In Chrome the Abstract and TOC dialog boxes are missing. This is not the case using Firefox and Safari. We are instructing students to NOT use Chrome whilst this bug exists. See attached screenshot.

**Comment by fpici** [comment]
![AbstractTOC.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58efcaa2b7100d001a59b5e8/125516c66e82c728ace21e0d46c99689379082aa9bdd9060e611b2843b492d762a10e17132d0e27ae7162f595b091bae425d5844fcf8db2baebe68268f4e17ff933c0120996048e6edc00db513bb27814e80b7be8f45c1ec342ce5838b5d73.png)

**Comment by fpici** [comment]
This problem must have resolved itself. we can cancel this.

**Comment by rotated8** [comment]
Sounds good. Thanks!
