### ISSUE TITLE
Change Honors Submission ownership from CBEARD4 to mchoi39 for https://etd.library.emory.edu/concern/etds/pk02c973d..

### ISSUE THREAD

**Issue by fpici** [emory-libraries/etd-issues#40]
Carlee Beard, the Honor's School Admin had to submit on student's behalf after she graduated in the Fall. Need to change https://etd.library.emory.edu/concern/etds/pk02c973d from CBEARD4 to mchoi39 for the record to publish.

**Comment by amiles4** [comment]
once @fpici submits the three candler ETDs then @rotated8 will submit as a fresh desk ticket.

**Comment by fpici** [comment]
Hi Coillin.

Shelly just got back to me on the two ETDs that she created on behalf of two Candler Graduates.
Both of these below have published, which surprises me. I thought the student's  NetID would drive the publication?

Anyway, here are the NetIds for these past students and the pids for their published records.

May I ask if you can change the ownership of these two and the Honors' one for Carlee referenced above.

Michelle Lewis ( MELEWI4):   https://etd.library.emory.edu/concern/etds/37720c77g

Kathryn Kimmel ( KSPANGL):   https://etd.library.emory.edu/concern/etds/1v53jx02k

Any questions, please let me know ...

**Comment by rotated8** [comment]
After following up with @fpici, these are not yet published, and we will wait for The Migration to land before creating a Freshdesk ticket (probably a week or two).

**Comment by fpici** [comment]
@rotated8 I believe this was completed 8.20.2018
