### ISSUE TITLE
Fall 2017 ETDs are NOT showing up in DiscoverE/Primo

### ISSUE THREAD

**Issue by fpici** [emory-libraries/etd-issues#41]
I am also going to assume that the upcoming spring 2018 ETDs -- once they publish --- will also need to be piped into DiscoverE/Primo

**Comment by amiles4** [comment]
@rosy1280 says: this is blocked by Fedora's product positioning work.  @rosy1280 is supposed to schedule a product positioning workshop with members of Fedora Steering/Leadership some time in July to begin conversations.

**Comment by fpici** [comment]
There was a temporary fix to this put in place by Laura Akerman and Elizabeth in June 2018.

**Comment by rotated8** [comment]
Since there is a fix in place, I am going to close this.
