### ISSUE TITLE
Copyright Questions on submission preview screen need to be broken out

### ISSUE THREAD

**Issue by fpici** [emory-libraries/etd-issues#42]
This is a 10 month old Laevigata ticket $716 that I am transferring here. I think it is a good one to prioritize. See screenshot

**Comment by fpici** [comment]
Here is a screenshot of the current view to students and their approvers.
![Screen Shot 2018-06-12 at 1.40.40 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58efcaa2b7100d001a59b5e8/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256455f16b7191a379f1162b4f5b5f5ecc3c4a4356bcbbd671f3e57862804e0ebcd3655b70ce3947f9ba811ab801ba21d94f8dbee8dc49d2f42f67b6d5db1063474f4dcbed5727a29941c95df443e84c52a3133767e6712431.png)

**Comment by amiles4** [comment]
@fpici says: this is something DCE created.  it seems like something that is a low hanging fruit.  

@rosy1280: we should add labels or list fields separately or both.

**Comment by rotated8** [comment]
curationexperts/laevigata#716

**Comment by mark-dce** [comment]
DCE is in the process of updating the submission forms (submission and review) and are updating the wording.  You might want to just do a quick fix to the review form for now against the `1.6-stable` stable branch that we can deploy sooner rather than later and then we can incorporate that into our work on the main 2.x branch.

**Comment by rotated8** [comment]
Sounds good. Thanks @mark-dce!

**Comment by rotated8** [comment]
Follow up on this ticket: I'm putting it back in 'In Progress' to get a version of it merged to master.

**Comment by mark-dce** [comment]
We're on it.
