### ISSUE TITLE
Allow user to save for later editing

### ISSUE THREAD

**Issue by fpici** [emory-libraries/etd-issues#43]
Ticket started in Laevigata #213. 

Save status of submission while student is editing
If they leave the application and come back later, prompt them to continue their work in progress
Student can keep editing their ETD as many times as they want until they are ready to submit the ETD to approver.

8 Months agao Val said: "One possible way to implement this would be to add a 'draft' workflow state so that the student always has ability to edit their ETD until they are finally ready to submit it for approval. We could probably just add a big 'Save my Draft' button under the checklist that saves the ETD but doesn't advance the workflow to the approver."

**Comment by amiles4** [comment]
@rosy1280 says: this will be addressed with the UI enhancements and partial save work.

**Comment by rotated8** [comment]
curationexperts/laevigata#213

**Comment by amiles4** [comment]
see #13

**Comment by fpici** [comment]
I believe this was taken care of during the 2.0 upgrade :-)
