### ISSUE TITLE
Maintain provenance log

### ISSUE THREAD

**Issue by fpici** [emory-libraries/etd-issues#44]
Application will maintain a "provenance log" that records every action performed on a stored document, including initial deposit, editing, approval, deletion, publication, submission to ProQuest, and any embargo events. This log will include the date and time, which user performed the action, whether the action was successful, and which documents were affected.

 Logs are in standardized Logger format
 Logs are date stamped and automatically rotated
 Logs are backed up automatically
 Logs should be visible in the UI by superusers
 Required fields are present:
 Date and time stamp
 user
 document id
 what action was performed
 whether the action was successful
 Logged actions are also logged to the object in question
 Logs must be retained for a minimum of 60 days

**Comment by fpici** [comment]
Also in Laevigata Tix # 238.

**Comment by rotated8** [comment]
curationexperts/laevigata#238

**Comment by amiles4** [comment]
@fipici says: the following are some important information to capture
* status
* when submitted
* approved
* embargos (set, changed, etc.)
* publishing
* confirmation of graduation
* sent to proquest

@rosy1280 wonders: if we expose the Fedora audit trail would some of this information be captured?

**Comment by rosy1280** [comment]
fedora audit trail may not be on by default.  this was taken off the table early on because of the cost.

**Comment by fpici** [comment]
Here is a screenshot of the current audit trail in Legacy ETDs. It is a Laney dissertation record log:
![Screen Shot 2018-06-27 at 1.49.45 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58efcaa2b7100d001a59b5e8/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256456f46b7191a379f116224f5b5a5ecc3c4a4356bcbbd671f3e57862804e0ebcd3655b70ce3947f9ba811ab801ba21d94f8dbee8dc49d2f42f67b6d5db1063474f4dcbed5727a19141c95df54be04f54ac143067e4702431.png)

**Comment by rosy1280** [comment]
A Mellon grant is being submitted by UCSD that may scope out this work for Hyrax.  Emory has been named a partner on the grant.

**Comment by fpici** [comment]
@rosy1280 This is great news Rosalyn. Thank you!!
