### ISSUE TITLE
Implement and customize the built in Hyrax help form

### ISSUE THREAD

**Issue by amiles4** [emory-libraries/etd-issues#45]
DCE will need to set up the form to email to the right location.

**Comment by devanshu-m** [comment]
@rotated8 @alexBLR  do we want to build off of the built in Hyrax contact form (as it is here: /contact) ?

**Comment by rotated8** [comment]
Yes, extending/replacing as appropriate.

**Comment by devanshu-m** [comment]
For the mailer, do we have a `to` email address? Also, should we keep `from` as the email address that was entered by the user when filling the form?
