### ISSUE TITLE
Mark Bussey would like to see a list of the embargoed PIDs in Legacy ETDs we should expect to migrate.

### ISSUE THREAD

**Issue by fpici** [emory-libraries/etd-issues#47]
Mark Bussey would like to see a list of the embargoed PIDs in Legacy ETDs we should expect to migrate.
This is something he just requested for this afternoon's Hosting Meeting.  Many thanks!

**Comment by rotated8** [comment]
This is a nice-to-have. Zo will work on getting a count, and list of the PIDs.

**Comment by fpici** [comment]
Hi folks.

I added the upcoming embargo pids to the “Samples for ETD Migration Testing Worksheet” on Friday and referenced it in the DCE Hosting minutes.

Here is the information in the June Agenda Notes:

2. Can Emory provide a list the embargoed PIDs we should expect to migrate or should DCE develop this list?

a. Fran here. I have a list of upcoming embargoes with a date range 6.26.2018‑9.8.2018. Anything
more, Zo or Collin or DCE will have to generate from legacy ETDs.

b. I just added the list of upcoming embargoes to our Samples for ETD Migration Testing Worksheet
(Tab 2018‑06‑20_FrAnna) located here:

https://docs.google.com/spreadsheets/d/1rx-pLoPrdRqiH7FN7H9Yb7JXvO17DJTl5E85SJCG7Us/edit#gid=1617100522
Hope this helps ☺


Frances Pici
Scholarly Repository Application Support Analyst
Scholarly Communications Office
Emory University Libraries and Information Technology
Robert W. Woodruff Library
540 Asbury Circle
Atlanta, GA 30322
404.727.7673
fpici@emory.edu<mailto:%7Cfpici@emory.edu>

Check out our new websites!
Scholarly Communications http://sco.library.emory.edu/index.html
Research Data http://researchdata.emory.edu/index.html

**Comment by alexBLR** [comment]
[embargoed__legacy_etds.txt](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58efcf72fdbefb001a9aa262/125516c66e82c728ace21e0d46ed9998229084a68aed807ca858f7952a5f18763d00b0693cc7f33ab0487e021b4d44be44095d4cf8fd812ff0e33e738f5b0bedd03f5f7cce6947a9aa9e0dfd50e474d412dcfce9c85ecafa3c2ded8a8a4c3e1b001e8dff5b31a99d5985.txt)
