### ISSUE TITLE
Primary PDF not showing up in record download

### ISSUE THREAD

**Issue by fpici** [emory-libraries/etd-issues#51]
We have three ETD submissions where the pdf cannot be downloaded. Pids: g732d907d; n009w2365; pc289j093.
We asked the student to resubmit with new record but we will retain the original record -- in error state --- so you can determine why these submissions failed.

**Comment by fpici** [comment]
I think I accidentally closed this when I meant to add another pid. Sorry.

**Comment by fpici** [comment]
Hi Collin. This problem persists and now Rollins students are experiencing it. We are contacting each student and asking them to re-submit a new record. I am leaving the problem pids in error mode so you can investigate and I have added more to this ticket.

Here is the full list -- so far -- of ETD submissions where we cannot access the pdf:

g732d907d; n009w2365; pc289j093; 9306sz356; jm214p174; sb3978350; xd07gs792; 5x21tf52z.

**Comment by amiles4** [comment]
After recognizing that it was not just a few students based on the Rollins situation yesterday, I have been going through every single summer submission this morning to try to find which ones are affected. It appears to be every single record with an embargo on it. I cannot be sure if this is new or not, but a number of Laney records that already went through initial review are part of this group. I find it hard to believe that Renee reviewed all these records without downloading the files first. Did something deploy that would have made all of these files inaccessible between when they were initially reviewed and the past week? I am updating the pids as we speak in the ETDs Log spreadsheet, but there are already 13 more than when Fran updated last night. https://docs.google.com/spreadsheets/d/10G4eYFhtpeCKw8PqQul-ncJPe0mgVkQMyTLfD23cpJA/edit#gid=248114908

**Comment by amiles4** [comment]
All embargoed records are affected, no matter their current status, including already published records.
Published Examples:
https://etd.library.emory.edu/concern/etds/k35694421?locale=en
https://etd.library.emory.edu/concern/etds/5m60qr94g?locale=en
https://etd.library.emory.edu/concern/etds/cn69m413j?locale=en

**Comment by fpici** [comment]
Hi Collin. It looks like DCE made an update July 27, 2017 to Version v1.6.9 that may have had an impact on the ETDs submitted and published. Not sure, but I hope this may help you pinpoint a problem.

**Comment by rotated8** [comment]
Hi @fpici, can you retest this issue, please? This should be fixed now.

**Comment by fpici** [comment]
@rotated8 Howdy Colin. Yes, you are correct. Anna and I confirm that this has been fixed. And THANK YOU!!

**Comment by rotated8** [comment]
Thanks!
