### ISSUE TITLE
SuperUser Notifications very slow to load.

### ISSUE THREAD

**Issue by fpici** [emory-libraries/etd-issues#58]
**Please replace the things in italics (_like this_).**

I believe there is a problem with _the Notifications listing_, because when _a SuperUser or School Approver with many Notifications_ does the following:

_Steps to reproduce the behavior, like_
_1. Log in_and Successfully authenticate from Emory NetID account
_2. Click on ''Login on the main ETD site''_
_3. Scroll down to 'Notifications Bell'_
_4. See error_These actions should ideally display our Notifications, and they do

they expected to see their notifications listed 

_ to see their notifications listed quickly_

but instead

_the listings take about 30 seconds to display each time the Notifications are accessed_.

I believe this affects _all_ of our users but especially the SuperUsers and the School Approvers and ADAPS the most because _because we are constantly checking the Notifications Tab each day _, and they are _especially_ impacted because _we have to wait 30 seconds time for a refreshed display_.

**Comment by rotated8** [comment]
We'll spend about half a day diagnosing, and up to half a day fixing in Hyrax, if possible.

**Comment by alexBLR** [comment]
Fran checked the speed of the notifications and I have tested it as well. The speed improved. Closing this ticket

**Comment by fpici** [comment]
Thank you!!

Frances Pici
Scholarly Repository Application Support Analyst
Scholarly Communications Office
Emory University Libraries and Information Technology
Robert W. Woodruff Library
540 Asbury Circle
Atlanta, GA 30322
404.727.7673
fpici@emory.edu<mailto:%7Cfpici@emory.edu>

Check out our new websites!
Scholarly Communications http://sco.library.emory.edu/index.html
Research Data http://researchdata.emory.edu/index.html
