### ISSUE TITLE
Laney Dropdown does not match what s in the SchoolsPrograms Spreadsheet

### ISSUE THREAD

**Issue by fpici** [emory-libraries/etd-issues#6]
Hello Everyone.

The Laney dropdown is not accurately reflecting the Departments and Departmental subfields that we sent in our box spreadsheet.
A handful of students have contacted us looking for their departments.

See attached highlighted spreadsheet.
BTW, this is also a ticket in Data Curation Experts Waffle Instance #28: https://curationexperts.freshdesk.com/support/tickets/28 
 if we want to merge the two.

Many thanks in advance!

**Comment by fpici** [comment]
[SchoolsProgramsSubRevisions1HighlightedMissingLaney.xlsx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58efcaa2b7100d001a59b5e8/125516c66e82c728ace21e0d46db97922c8d8fbabffbb044b65cfd871a5325412c12aa38798aed3bee6a7206070317fb191c0a1081a0ca68ffe86b0cdb025ea4c3714d3484624bf9ebc60db513bf71894781b2b48e1a95ea3e20e08b8f4e6c1e0d10dda95827bc8b099906a214bc141ff1512469f474367646911f772a6e632ea2f8df5183972d.xlsx)

**Comment by alexBLR** [comment]
Ok. I started working on this one @fpici

**Comment by fpici** [comment]
@alexBLR  Hi Zo. I just checked the dropdown and it looks like I am still missing the subfields for Biological and Biomedical Sciences. See my screenshot. I am checking on Chrome
![Screen Shot 2018-01-18 at 1.08.32 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58efcaa2b7100d001a59b5e8/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77226455fb6b7191a379f112234f5c5d5ecc3c4a4356bcbbd671f3e57862804e0ebcd3655b70ce3947f9ba811ab801ba21d94f8dbee8dc49d2f42f67b6d5db1063474f4dcbed5727a29841c95df74de3445ca51b3566e1752431.png)

**Comment by fpici** [comment]
@rotated8 I just checked the fixes in ETD Q/A. Looks fabulous!! Thank you

**Comment by fpici** [comment]
@rotated8 Changes deployed to Production look FABULOUS! Thank you!
