### ISSUE TITLE
Replace image on ETD Main Page with attached new image

### ISSUE THREAD

**Issue by fpici** [emory-libraries/etd-issues#63]
Is there any way you can look at this new image and see if it will work? It is part of a closed ticket 748: https://github.com/curationexperts/laevigata/issues/748 and the sizing specs from Mark Bussey in 2017 are these:
![0050105-15bm-f294](https://user-images.githubusercontent.com/7809072/46094948-51b07800-c189-11e8-98ae-32cba85eceb5.jpg)

Crop with 7.35:1 aspect ratio actually probably closer to 6.5:1 for the widest possible monitor.

**Comment by fpici** [comment]
@rotated8 Good morning Collin. I just noticed the new image on qa-etd.library.emory.edu. Is there any way to zoom out of this image or expand the frame to capture more of the picture and the students walking in front of the Emory University wall.  On an IPad and an iPhone all you see is Emory Univ. I was hoping with the new Hyrax upgrade we would have more flexibility with a new image. Let me know what you think. If nothing can be done to improve this image, I think we should stick with the tulips. :-)

**Comment by rotated8** [comment]
Since we're going to deploy tomorrow, let's leave it the way it is for now, and we'll get the web team to give us a banner for the next deploy.
