### ISSUE TITLE
Prepare final records for migration.

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/etd-issues#65]
These records migrated successfully, and require no action:
emory:s1q70 -> kk91fm586
emory:8507k -> 9w032410x
emory:rhmrp -> bc386k30s
emory:pgpjx -> ff365638h

These records failed migration or migrated without all their files, and have had some of their files stripped:
emory:r8ks7 -> q237ht116
emory:fzmmq -> 4b29b7216
emory:7s1md
emory:pg74x
emory:s00c9
emory:bpqzr
emory:pshzp
emory:d9276
emory:d7q71
emory:bpn7n

These records failed migration, but did not have their files stripped:
emory:ft5gj
emory:rhvp4
emory:pj14f
emory:bnk0d
emory:fzj29
emory:g09vv

The files are in [Box](https://emory.app.box.com/folder/53401022907), and need their fixity verified. Once fixity is verified for the records in the third group, their non-pdf files should be removed from the legacy system.

**Comment by rotated8** [comment]
Primary effort should be towards verifying the fixity of the files in Box for the records that have had files stripped. This should be accomplished by restoring a snapshot of Fedora data to the QA environment, with Middleware's help, and querying that Fedora instance. As time permits,  file names should be verified as well.

Additionally, the records that did not have their files stripped should have their fixity verified via the production Fedora, and, as time permits, their filenames verified as well.

**Comment by alexBLR** [comment]
Get both sha and md5 checksums.

**Comment by alexBLR** [comment]
emory:r8ks7 - 2
emory:fzmmq - 10
emory:7s1md - 1
emory:pg74x - 1
emory:s00c9 - 4
emory:bpqzr - 3
emory:pshzp - 3
emory:d9276 - 19
emory:d7q71 - 3
emory:bpn7n - 3

total : 49

**Comment by fpici** [comment]
@rotated8 Hi Collin and Bess. All supplementary files stripped and we are ready to rock and roll!!
