### ISSUE TITLE
Please Add a new Rollins Approver to EPI and GLEPI department.

### ISSUE THREAD

**Issue by fpici** [emory-libraries/etd-issues#68]
RSPH Admin just requested that we add Nicole Regan (NFERLAN) as an approver for EPI (Epidemiology) and GLEPI (Global Epidemiology) records.

Many thanks!

**Comment by rotated8** [comment]
For spring, we should ask the schools to provide all approver changes by a certain date, so we can submit them all at once to DCE on that date.

This has been added to Freshdesk.

**Comment by fpici** [comment]
I totally agree!!

**Comment by rotated8** [comment]
@fpici NFERLAN is already an approver for these departments. Can you confirm that is the correct netid?

**Comment by fpici** [comment]
@rotated8 Hi Collin. I am checking with the RSPH Manager who requested the addition and also checking with NFERLAN (Nicole) to see if she has access. I will let you know when they reply :-)

**Comment by fpici** [comment]
@rotated8 Hi Collin. I just spoke to NFERLAN (Nicole) and her boss Robie. Yes, she was an early Approver and left Emory but now she is back. 
So, she needs to be removed from Health Policy and Management - MSPH 
and from Hubert Department of Global Health - MPH. 
We need to keep her in Epidemiology and GLEPI. 

So sorry this was confusing but they confused me :-)
