### ISSUE TITLE
Please reinstate embargo on an expired migrated legacy ETD restriction 

### ISSUE THREAD

**Issue by fpici** [emory-libraries/etd-issues#69]
We have another Legacy ETD record that needs to have the embargo reinstated and extended. 

Author: Woolheater, Ashley Lynette
URL: https://etd.library.emory.edu/concern/etds/ks65hc85n?locale=en
Restrictions: Abstract, TOC, and Files until 10.24.2021.

Very similar to Tix #53 :-)

Many thanks!

**Comment by rotated8** [comment]
This ETD is in #53, and has already been submitted to Freshdesk. Closing as duplicate.

**Comment by fpici** [comment]
@rotated8 Hi Collin. So sorry. I did not realize this ETD was already in Tix #69 :-( Good eye :-)
