### ISSUE TITLE
The College Honors Department Dropdown is also missing several entries

### ISSUE THREAD

**Issue by fpici** [emory-libraries/etd-issues#7]
The College Honors Department Dropdown is also missing several entries. Using the SchoolsProgramsSubRevisions spreadsheet, I highlighted the missing departments in yellow. 
I also highlight  "Women's, Gender, and Sexuality Studies" which is what should be in the dropdown instead of "Women's Studies."  I attach the highlighted spreadsheet for you.

Also this is also a Freshdesk ticket #29: https://curationexperts.freshdesk.com/support/tickets/29 that we may eventually want to merge.

**Comment by fpici** [comment]
[SchoolsProgramsSubRevisions1HighlightedMissingCollegeHonors.xlsx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58efcaa2b7100d001a59b5e8/125516c66e82c728ace21e0d46db97922c8d8fbabffbb044b65cfd871a5325412c12aa38798aed3bee6a7206070317fb191c0a1081a0ca68ffe86b03d50057b88638272b986253efaa9e0dff43e57ade1cc1a4b6984991ea3521e3838b196b1c061d8eff5d34f29943c00ca04ef35147e6426837b92b6f3612d60c7f3e6a6e2caaf9de54818065a7be152650c1f1a9.xlsx)

**Comment by alexBLR** [comment]
Ok. I started working on this one @fpici

**Comment by fpici** [comment]
@alexBLR Hi Zo. The fixes were deployed to ETD QA. I checked and they all look great!! Thank Thank you

**Comment by fpici** [comment]
@alexBLR Changes deployed to Production look FABULOUS! Thank you!
