### ISSUE TITLE
Post Migration Review_ SuperUser Edit record field

### ISSUE THREAD

**Issue by fpici** [emory-libraries/etd-issues#70]
**Please replace the things in italics (_like this_).**

I believe there is a problem with _SuperUser Edit field for migrated legacy records_, because when _I edit these four migrated Emory College records the School field changes to Laney which is a fixed un-editable field_ does the following:

_Steps to reproduce the behavior, like_
_1. Log in_as a SuperUser
_2. Click on 'Edit Record in Migrated Legacy record....'_
_3. Scroll down to 'School field '_
_4. See error_School field has changed to Laney

they expected 

_to see the School field display Emory College_

but instead

_School field has changed to Laney and cannot be changed back to Emory College and one changed Emory College and needs to be Laney to sav successfully_.

This affects _2 specific records_ of our users because _these 2 records are of 16 records that have to be edited in order to add the stripped supplemental files_, and they are _a qualifier_ impacted because _another reason_. 

Are you able to force a School field change on the back-end? This way I can add these supplemental files and have y'all correct the fixed School field.  I attach the 2 problem pids: x920fx98z; rr171z280. 
I ran into some trouble with 3 of the migrated records. When I hit the Edit button, the School changed from Emory College to Laney and Laney to Emory College. I am adding these to the pids that Collin or DCE will have to fix on the back-end so I can save the records. Here are the pids that switched Emory College to Laney: x920fx98z; rr171z280. I also have one where the school changed from Laney to Emory College: Here is the pid: zs25x9505 .

Also referenced in Google sheet here: https://docs.google.com/spreadsheets/d/1anTqeRHl4MJNoQ7nVy2YvKG0n2PwUQUmxKXluwDJX-E/edit#gid=0

**Comment by rotated8** [comment]
Hi Fran, these ETDs appear to have lost their departments when their school changed. Can you add those here please?

**Comment by fpici** [comment]
Hi Collin. I added the department for all three BUT this one is still saving as Laney and should be College Honors: https://etd.library.emory.edu/concern/etds/rr171z280?locale=en
AND
this one is still saving as Emory College and should be Laney: https://etd.library.emory.edu/concern/etds/zs25x9505?locale=en

:-)
