### ISSUE TITLE
Spring 2018 ETD NOT findable in search

### ISSUE THREAD

**Issue by fpici** [emory-libraries/etd-issues#72]
**Please replace the things in italics (_like this_).**

I believe there is a problem with _the search and or indexing functionality for Kaitlin Piper's SPring 2018 Published record_, because when _any user_ does the following:

_Steps to reproduce the behavior, like_
_1. Log in_ ETDs
_2. Click on 'Search field'_
_3. Scroll down to 'Types in Name or record Title'_
_4. See error_

they expected 

_to find the record_

but instead

_the record is NOT discoverable_.

I believe this affects _small_ of our users because _not many people may be looking for Piper's record_, and they are _a qualifier_ impacted because _another reason_.

I confirmed with RSPH that Kaitlin (KPIPER2) did graduate in Spring 2018. Here is the Pid for the record: https://etd.library.emory.edu/concern/etds/qj72p719f?locale=en

Many thanks!

**Comment by fpici** [comment]
Hello again. This approved record also has the wrong School listed. The School should be RSPH but after editing the TOC, the School switched to Laney Graduate School.  This is an un-editable field for a User/Superuser. Can you change the School back to RSPH and then we will see if the record publishes properly. Many thanks!

**Comment by rotated8** [comment]
Second ETD: https://etd.library.emory.edu/concern/etds/79407x20j

**Comment by fpici** [comment]
Hi Collin. I confirmed that Piper, Kaitlin is still not findable in ETDs searching by her name and or her record's title?
