### ISSUE TITLE
Partnering Agencies Report for RSPH

### ISSUE THREAD

**Issue by fpici** [emory-libraries/etd-issues#80]
RSPH Director wants to have a report that will show how many RSPH students submitted a thesis where they added Partnering Agencies to their record and what Partnering Agencies they chose . Her requested date range is **Fall 2017/spring 2018/summer 2018**. Her deadline is ASAP and she apologizes for the last minute request.

**Comment by fpici** [comment]
Howdy Collin. I just spoke with the RSPH Admin and she said : "Unfortunately, we will need the report before that time (January 2019)." Any suggestions on how we can proceed with this earlier to satisfy Rollins?

**Comment by rotated8** [comment]
Hi Fran, would a date range of Aug. 1, 2017 to July 31, 2018 be appropriate?

**Comment by fpici** [comment]
Hi Collin. Checking with Robie @RSPH just to be sure :-)

**Comment by fpici** [comment]
Collin, Bess et al ... From Robie at RSPH: "Dear Fran and the ETD Developers,
Thank you so much for getting this information to me. Thank you for going above and beyond to get this information before the holidays. Your extra efforts are truly appreciated.
Thanks again."
Robie Freeman Michaux, M.Ed.
Director of Enrollment Services/Registrar
