### ISSUE TITLE
Spring 2018 Graduate's record Liss, Dara is not findable and maybe did not publish.

### ISSUE THREAD

**Issue by fpici** [emory-libraries/etd-issues#82]
**Please replace the things in italics (_like this_).**

I believe there is a problem with _a feature_, because when _someone_ does the following:

_Steps to reproduce the behavior, like_
_1. Log in_
_2. Click on '....'_
_3. Scroll down to 'enter name: Liss, Dara.'_
_4. See error_

they expected 

_o pull up her published Spring 2018 record_

but instead

_it is not findable_.

I believe this affects _small_ of our users because _not many people will look for her master's thesis_, and they are _a qualifier_ impacted because _another reason_.

According to Emory College Admin, Dara did graduate in the Spring 2018 and her record was approved. Record is still not findable in ETDs when searching by her name or by her record's title? Looks like Liss's record is still in Approved status and did not publish? https://etd.library.emory.edu/concern/etds/hd76s009b?locale=en

**Comment by rotated8** [comment]
Superseded by #85
