### ISSUE TITLE
Honors graduate records did not publish

### ISSUE THREAD

**Issue by fpici** [emory-libraries/etd-issues#85]
The following Honors record submissions are NOT findable by name or by record title. Honors admin confirms they all graduated.

Can you force publish these records:

1) Fuscoe, Claire graduated in Spring 2018.
Record is located here: https://etd.library.emory.edu/concern/etds/4b29b598d?locale=en

2) Hayes, Kelsey in Spring 2018?
Record located here: https://etd.library.emory.edu/concern/etds/m326m1782?locale=en  

3) Wang, Jesse in Spring 2018?
Record located here: https://etd.library.emory.edu/concern/etds/zc77sq117?locale=en

4) Zhang, Zuoyu in Spring 2018?
Record located here: https://etd.library.emory.edu/concern/etds/736664496?locale=en

**Comment by rotated8** [comment]
Hi Fran,

None of these students show up in the registrar's data, which is suspicious. I will follow up with them.

**Comment by fpici** [comment]
Hi Collin. Is this true for Tix 83, Tix 84, and Tix 86 too?

**Comment by rotated8** [comment]
No, I have sent those over to Bess, and are in progress.

**Comment by rotated8** [comment]
I am adding Dara Liss here as well, as she also does not show up in the registrar's data. https://etd.library.emory.edu/concern/etds/hd76s009b?locale=en
