### ISSUE TITLE
Embargo settings do not change after editing

### ISSUE THREAD

**Issue by fpici** [emory-libraries/etd-issues#9]
As a student who has submitted a thesis/dissertation where the Approver has requested changes to my embargoed files, I want to see my changes reflected in the re-submission, so that I can comply with my approver's suggestions.

**Comment by fpici** [comment]
Hello there. I did some testing in QA using this pid: (xp68kg21m). The original submission was embargoed. After I, as an  Approver requested changes to un-embargo, I un-embargoed the files and re-submitted and choosing "Request Review"  but the changes to the embargo were NOT saved. The generate preview indicates that the un-embargo was saved but it is not reflected in the record. (see screenshot)
![NoEmbargoedContent.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58efcaa2b7100d001a59b5e8/125516c66e82c728ace21e0d46c69bbf2e8082bb88e6ba478752fe802c4833316546b3397f8fe62bab0021435a0e4ca4455c5740aaac8b28a3b13c708b0e0be5d9390971d42103eee9dc4be05ce36ade0d97bcae8b4bcae93824e482894c3d1e041a8dfd4f78.png)

**Comment by fpici** [comment]
I created another test record in Staging and the behavior is different. In Staging, I, as a Student do NOT see the "Review" dropdown to "Request Review" after I make the necessary edits to my record.  As a result, I cannot make the necessary Re-Submission changes. Pid:  (qn59q396v)

**Comment by fpici** [comment]
Also, we discovered that if you make duration changes to the embargo and resubmit, this will save properly : Pid in QA: (sx61dm28w) and if you start with an Un-Embargoed file and then change to Embargoed, this does save properly: Pid in Staging: (1831cj92z).

**Comment by fpici** [comment]
6.13.2018: Medium - should be addressed with migration tool work.

**Comment by fpici** [comment]
3.19.2018: Collin says: "Field does not show up in the edit form. Missing from terms?"

**Comment by fpici** [comment]
Medium - should be addressed with Migration tool.

**Comment by rosy1280** [comment]
This may be resolved or improved with https://github.com/curationexperts/laevigata/issues/1035

**Comment by fpici** [comment]
We tested in QA and in Prod after the 9.24.2018 release and this is still a problem. If a student changes their embargo after an Approver Requests them to do so,  the changed embargo settings do not save nor apply.

**Comment by fpici** [comment]
Hi there. I cannot successfully save a record after I try to change the embargo. I started with a 2-year embargo, then placed the record in 'changes required' status, and when I tried to save the record I received this error See screenshot:
![Screen Shot 2019-01-10 at 2.15.32 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58efcaa2b7100d001a59b5e8/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77226455f36b7191a37af1132e4f5c5d5ecc3c4a4356bcbbd671f3e57862804e0ebcd3655b70ce3947f9ba811ab801ba21d94f8dbee8dc49d2f42f67b6d5db1063474f4dcbed5727a19e41c95df24ce04952ac14336be6762431.png)

**Comment by fpici** [comment]
Hi there. I just tried this again and the record still displays an embargo status in the upper banner even though there is no embargo on the record. Using this record: https://qa-etd.library.emory.edu/concern/etds/g158bj19x. See screenshot
![Screen Shot 2019-01-15 at 11.22.01 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58efcaa2b7100d001a59b5e8/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77226455f66b7191a379ee0c2953415f4fbc30254d58eeb9cb74fce36f34985619e8806f5770c23515faed801cba06ba208a1d85beb4de1ac5fa2137a5dad11b61435c52dcbd4f3fb29b4ac259f34fe64853ad173765e27f326e0a.png)

**Comment by rotated8** [comment]
Check the note in the Table of Contents: "[Table of contents embargoed until None - open access immediately post-graduation]". I expect the expiration date has been updated, but since this one hasn't been approved and graduated, it will continue to show an embargo.

**Comment by fpici** [comment]
Ah, I see the note in the TOC. So, we really have to wait until an approved record has published before the banner changes, yes?

**Comment by rotated8** [comment]
That seems to be the case, yes.

**Comment by fpici** [comment]
Okay, I approve this ticket in QA :-)
