### ISSUE TITLE
SuperUsers and Approvers changes

### ISSUE THREAD

**Issue by fpici** [emory-libraries/etd-issues#94]
Remove Freeman Michaux, Robie (RFREEM2) as a Rollins ADAP 
AND
Remove Miles, Anna (amiles4)  as an SCO SuperUser. 
Please remove this access in Prod, QA, and Test environments. Many thanks!

**Comment by rotated8** [comment]
Is this all the changes for the Spring semester? I'd like to avoid opening multiple tickets with DCE about approver changes.

**Comment by rotated8** [comment]
Please add TWO new Admin Superusers to ETD Prod, QA, and Test environments.

Head of SCO, Jody Bailey (JEBAIL5) [jody.bailey@emory.edu](mailto:jody.bailey@emory.edu);
SCO Library Specialist Sr. Kylie Shannon (KSHANN4) [kylie.shannon@emory.edu](mailto:kylie.shannon@emory.edu)

**Comment by fpici** [comment]
Hi Collin. I am not sure if RSPH will ask us to change some of their ADAPs around to compensate for the departure of Robie Freeman. I checked back with them two weeks ago and they are currently in flux. So, to answer your questions  if there will be any more this Spring ... I don't know. :-)

**Comment by rotated8** [comment]
SuperUser changes have been communicated to DCE. I would like to wait to do all the approver changes at once. Each set will require DCE's availability, both to do the work, and deploy it.

**Comment by fpici** [comment]
Thank you Collin. Makes sense :-)
